# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 소셜로봇연구회 Social Robot SIG
email: minsu@etri.re.kr
description: >- # this means to ignore newlines until "baseurl:"
  한국로봇학회 소셜로봇연구회 홈페이지입니다. The hompage for Social Robot SIG of Korea Robotics Society.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
logo: "/assets/images/kros_logo.png"
og_image: /assets/images/kros_logo.png

search: true
timezone: Asia/Seoul
breadcrumbs: true  # disabled by default

include: ["_pages"]

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

github: [metadata]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
